# Generated by Django 6.0 on 2025-12-31 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='0000', max_length=20, unique=True),
        ),
    ]
